/** @format */

export let GET_REQUEST = "GET_REQUEST";
export let GET_SUCCESS = "GET_SUCCESS";
export let GET_ERROR = "GET_ERROR";

//GET REQUEST for singleShoesPage
export let GET_SINGLE_SHOES_REQUEST = "GET_SINGLE_SHOES_REQUEST";
export let GET_SINGLE_SHOES_SUCCESS = "GET_SINGLE_SHOES_SUCCESS";
export let GET_SINGLE_SHOES_ERROR = "GET_SINGLE_SHOES_ERROR";
