// FOR USER LOGIN
export let LOGIN_REQUEST="LOGIN_REQUEST";
export let LOGIN_SUCCESS="LOGIN_SUCCESS";
export let LOGIN_ERROR="LOGIN_ERROR";

// FOR UER REGISTER
export let REGISTER_REQUEST="REGISTER_REQUEST";
export let REGISTER_SUCCESS="REGISTER_SUCCESS";
export let REGISTER_ERROR="REGISTER_ERROR";
